version: 2.1
workflows:
  deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
  trigger-devdoc:
    jobs:
      - trigger-devdoc:
          filters:
            branches:
              only:
                - master
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:11
    environment:
      - SOURCE_BRANCH: master
      - TARGET_BRANCH: gh-pages
    steps:
      - checkout
      - deploy:
          name: Deploy site
          command: |
            if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME
              git clone $CIRCLE_REPOSITORY_URL project

              cd project
              rm -rf .circleci
              npx uncrate
              git checkout $TARGET_BRANCH
              cp -r dist/* .
              rm -rf dist

              git add -A
              git commit -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]" --allow-empty
              git push origin $TARGET_BRANCH

              curl -u ${CIRCLE_API_USER_TOKEN}: \
                   -d build_parameters[CIRCLE_JOB]=deploy_docker \
                   https://circleci.com/api/v1.1/project/<vcs-type>/<org>/<repo>/tree/<branch>
            fi

  trigger-devdoc:
    steps:
      - run: curl -X POST "https://circleci.com/api/v1.1/project/github/Conflux-Chain/conflux-developer-site/build?circle-token=${CIRCLE_API_USER_TOKEN}"
